config/routes.rb
Rails.application.routes.draw do
  resources :sensor_logs
  resources :log_view

  mount API => "/api"

end

app/models/log_view.rb
class LogView < ActiveRecord::Base
end

app/models/sensor_log.rb
class SensorLog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/log_view_controller.rb
class LogViewController < ApplicationController
  before_action :set_sensor_log, only: [:show]

  # GET /sensor_logs
  # GET /sensor_logs.json
  def index
#    @sensor_logs = SensorLog.all
#     @sensor_logs = SensorLog.where('log_datetime LIKE ?', '2015-07-25%')
     if params[:datepicker] != nil
       @sensor_logs = SensorLog.where('log_datetime LIKE ?' ,params[:datepicker] + " " + params[:time] + '%')
     else
       @sensor_logs = SensorLog.all
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor_log
      @sensor_log = SensorLog.find(params[:id])
#      @sensor_log = SensorLog.find([2,5,10])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_log_params
      params.require(:sensor_log).permit(:log_datetime, :sensor_id, :sequence_num, :temperture, :hermidity, :sunshine_degree, :infrared)
    end
end

app/controllers/sensor_logs_controller.rb
class SensorLogsController < ApplicationController
  before_action :set_sensor_log, only: [:show, :edit, :update, :destroy]

  # GET /sensor_logs
  # GET /sensor_logs.json
  def index
    @sensor_logs = SensorLog.all
  end

  # GET /sensor_logs/1
  # GET /sensor_logs/1.json
  def show
  end

  # GET /sensor_logs/new
  def new
    @sensor_log = SensorLog.new
  end

  # GET /sensor_logs/1/edit
  def edit
  end

  # POST /sensor_logs
  # POST /sensor_logs.json
  def create
    @sensor_log = SensorLog.new(sensor_log_params)

    respond_to do |format|
      if @sensor_log.save
        format.html { redirect_to @sensor_log, notice: 'Sensor log was successfully created.' }
        format.json { render :show, status: :created, location: @sensor_log }
      else
        format.html { render :new }
        format.json { render json: @sensor_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensor_logs/1
  # PATCH/PUT /sensor_logs/1.json
  def update
    respond_to do |format|
      if @sensor_log.update(sensor_log_params)
        format.html { redirect_to @sensor_log, notice: 'Sensor log was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor_log }
      else
        format.html { render :edit }
        format.json { render json: @sensor_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensor_logs/1
  # DELETE /sensor_logs/1.json
  def destroy
    @sensor_log.destroy
    respond_to do |format|
      format.html { redirect_to sensor_logs_url, notice: 'Sensor log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor_log
      @sensor_log = SensorLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_log_params
      params.require(:sensor_log).permit(:log_datetime, :sensor_id, :sequence_num, :temperture, :hermidity, :sunshine_degree, :infrared)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_view_helper.rb
module LogViewHelper
end

app/helpers/sensor_logs_helper.rb
module SensorLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SensorLogs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/log_view/index.html.erb
<br>
<h1>Viewing sensor logs</h1>

<input class="datepicker" type="text" name="datepicker" id="datetime"></input>
    <select id="target-hour" class="form-control" name="time">
      <option value="00"> 0:00 - 1:00
      <option value="01"> 1:00 - 2:00
      <option value="02"> 2:00 - 3:00
      <option value="03"> 3:00 - 4:00
      <option value="04"> 4:00 - 5:00
      <option value="05"> 5:00 - 6:00
      <option value="06"> 6:00 - 7:00
      <option value="07"> 7:00 - 8:00
      <option value="08"> 8:00 - 9:00
      <option value="09"> 9:00 - 10:00
      <option value="10"> 10:00 - 11:00
      <option value="11"> 11:00 - 12:00
      <option value="12"> 12:00 - 13:00
      <option value="13"> 13:00 - 14:00
      <option value="14"> 14:00 - 15:00
      <option value="15"> 15:00 - 16:00
      <option value="16"> 16:00 - 17:00
      <option value="17"> 17:00 - 18:00
      <option value="18"> 18:00 - 19:00
      <option value="19"> 19:00 - 20:00
      <option value="20"> 20:00 - 21:00
      <option value="21"> 21:00 - 22:00
      <option value="22"> 22:00 - 23:00
      <option value="23"> 23:00 - 24:00
    </select>

    <button type="button" id="loading-btn" data-loading-text="Loading..." class="btn btn-primary btn-block">Loading</button>

<!--
<table>
  <thead>
    <tr>
      <th>Log datetime</th>
      <th>Sensor</th>
      <th>Sequence num</th>
      <th>Temperture</th>
      <th>Hermidity</th>
      <th>Sunshine degree</th>
      <th>Infrared</th>
      <th colspan="3"></th>
    </tr>
  </thead>
-->

<!--
  <tbody>
    <% @sensor_logs.each do |sensor_log| %>
      <tr>
        <td><%= sensor_log.log_datetime %></td>
        <td><%= sensor_log.sensor_id %></td>
        <td><%= sensor_log.sequence_num %></td>
        <td><%= sensor_log.temperture %></td>
        <td><%= sensor_log.hermidity %></td>
        <td><%= sensor_log.sunshine_degree %></td>
        <td><%= sensor_log.infrared %></td>
      </tr>
    <% end %>
  </tbody>
-->
</table>

<script>
$('#loading-btn').click(function () {
  var targetDate = $('#datetime').val();
  if (!targetDate) {
    alert('対象日付を選択してください');
    return;
  }

  var targetHour = $("#target-hour").val();
  if (!targetHour) {
    alert('対象時間を選択してください');
    return;
  }

  $.ajax({
        url :"http://192.168.56.101:3000/api/mobile_locations/by_hour/",
        dataType : "jsonp",
        data : {
          //date : '2014-09-24',
          //hour : 17
          date : targetDate,
          hour : targetHour
        }
        }).done(function(data){
            if (data.length == 0) {
              alert("該当データがありませんでした");
            }
            else {
              alert('データ読込終了しました');
            }
        }).fail(function(jqXHR, textStatus, errorThrown){
          //console.log('error');
          alert(textStatus);
        }).always(function(data){
          //clearDiagram();
        });
});

$('.datepicker').datepicker({
    format: 'yyyy-mm-dd'
});
</script>

app/views/sensor_logs/_form.html.erb
<%= form_for(@sensor_log) do |f| %>
  <% if @sensor_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor_log.errors.count, "error") %> prohibited this sensor_log from being saved:</h2>

      <ul>
      <% @sensor_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :log_datetime %><br>
    <%= f.datetime_select :log_datetime %>
  </div>
  <div class="field">
    <%= f.label :sensor_id %><br>
    <%= f.number_field :sensor_id %>
  </div>
  <div class="field">
    <%= f.label :sequence_num %><br>
    <%= f.number_field :sequence_num %>
  </div>
  <div class="field">
    <%= f.label :temperture %><br>
    <%= f.text_field :temperture %>
  </div>
  <div class="field">
    <%= f.label :hermidity %><br>
    <%= f.text_field :hermidity %>
  </div>
  <div class="field">
    <%= f.label :sunshine_degree %><br>
    <%= f.text_field :sunshine_degree %>
  </div>
  <div class="field">
    <%= f.label :infrared %><br>
    <%= f.text_field :infrared %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/sensor_logs/edit.html.erb
<h1>Editing Sensor Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor_log %> |
<%= link_to 'Back', sensor_logs_path %>

app/views/sensor_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensor Logs</h1>

<input class="datepicker" type="text"></input>
 
<table>
  <thead>
    <tr>
      <th>Log datetime</th>
      <th>Sensor</th>
      <th>Sequence num</th>
      <th>Temperture</th>
      <th>Hermidity</th>
      <th>Sunshine degree</th>
      <th>Infrared</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensor_logs.each do |sensor_log| %>
      <tr>
        <td><%= sensor_log.log_datetime %></td>
        <td><%= sensor_log.sensor_id %></td>
        <td><%= sensor_log.sequence_num %></td>
        <td><%= sensor_log.temperture %></td>
        <td><%= sensor_log.hermidity %></td>
        <td><%= sensor_log.sunshine_degree %></td>
        <td><%= sensor_log.infrared %></td>
        <td><%= link_to 'Show', sensor_log %></td>
        <td><%= link_to 'Edit', edit_sensor_log_path(sensor_log) %></td>
        <td><%= link_to 'Destroy', sensor_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor log', new_sensor_log_path %>

<script>
//alert('hoge');
//alert($('#datepicker').val());
//$('#datepicker').datepicker();
$('.datepicker').datepicker({
    format: 'yyyy/mm/dd',
    startDate: '-3d'
});
</script>

app/views/sensor_logs/new.html.erb
<h1>New Sensor Log</h1>

<%= render 'form' %>

<%= link_to 'Back', sensor_logs_path %>

app/views/sensor_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Log datetime:</strong>
  <%= @sensor_log.log_datetime %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @sensor_log.sensor_id %>
</p>

<p>
  <strong>Sequence num:</strong>
  <%= @sensor_log.sequence_num %>
</p>

<p>
  <strong>Temperture:</strong>
  <%= @sensor_log.temperture %>
</p>

<p>
  <strong>Hermidity:</strong>
  <%= @sensor_log.hermidity %>
</p>

<p>
  <strong>Sunshine degree:</strong>
  <%= @sensor_log.sunshine_degree %>
</p>

<p>
  <strong>Infrared:</strong>
  <%= @sensor_log.infrared %>
</p>

<%= link_to 'Edit', edit_sensor_log_path(@sensor_log) %> |
<%= link_to 'Back', sensor_logs_path %>